### ISSUE TITLE
Add an option to build with statically linked Guile

### ISSUE THREAD

**Issue by stikonas** [schierlm/gnu-autogen-bootstrapping#5]
https://github.com/schierlm/gnu-autogen-bootstrapping/blob/d169cf4f50bd9c1561828cef1a9b5b55f464ab92/bootstrap.sh#L77

Should be as simple as adding variable
`$(pkg-config guile-"${GUILE_VERSION}" --libs ${STATIC})`
where STATIC="--static" for static build or empty for dynamic

**Comment by schierlm** [comment]
Not sure if you also need to pass `-static` to the C compiler (in case your compiler/libc support both static and dynamic linking).

While we are at it, we probably want to replace `gcc` by `${CC:-gcc}`.

Feel free to send a PR. Or I can have a look at it next week.

**Comment by stikonas** [comment]
Indeed, we can also add variables for $CC and I think $CFLAGS which is empty by default.

I might send PR for this, but I'll possibly get [live-bootstrap](https://github.com/fosslinux/live-bootstrap/) first into the state where I can easily test [gnu-autogen-bootstrapping](https://github.com/schierlm/gnu-autogen-bootstrapping) in it.

**Comment by schierlm** [comment]
If you have any idea how to get Debian's libguile build statically (not against dynamic libraries which fails), I'd like to add the CI job back. Now I just "defused" it by ignoring the error status.

**Comment by stikonas** [comment]
> If you have any idea how to get Debian's libguile build statically (not against dynamic libraries which fails), I'd like to add the CI job back. Now I just "defused" it by ignoring the error status.

I'm a bit confused what fails. Do you mean a new Debian libguile static build fails? Because earlier we were just doing dynamic build.

**Comment by schierlm** [comment]
I tried to bootstrap autogen using statically linked Guile on Debian (or rather Ubuntu on Github CI, but it also happens with Debian bullseye):

https://github.com/schierlm/gnu-autogen-bootstrapping/blob/f9c85c9093c6d9b5447bc85f6beeeeb47082d390/.github/workflows/bootstrap.yml#L59-L60

But it does not work since `pkg-config -static` includes a `.so` file and gcc rightfully complains it cannot statically link against a dynamic object:

https://github.com/schierlm/gnu-autogen-bootstrapping/actions/runs/3093430030/jobs/5005785071#step:4:91

And I have no idea why pkg-config is doing this and how one can fix it so that static autogen build can be tested on Debian / Ubuntu CI.

**Comment by stikonas** [comment]
Have you installed static versions of gmp and libunistring?

**Comment by schierlm** [comment]
I installed

https://github.com/schierlm/gnu-autogen-bootstrapping/blob/f9c85c9093c6d9b5447bc85f6beeeeb47082d390/.github/workflows/bootstrap.yml#L56

and (I believe)

https://packages.debian.org/bullseye/amd64/libunistring-dev/filelist
https://packages.debian.org/bullseye/amd64/libgmp-dev/filelist

contain both static and dynamic versions.

**Comment by stikonas** [comment]
Could it be that you need to set LDFLAGS rather than CFLAGS?

**Comment by schierlm** [comment]
No idea. I don't use LDFLAGS variable for anything, not sure whether gcc will pick it up internally somewhere. But no big deal if it does not work in CI, as long as it works in live-bootstrap.
